# Configuración para H2
spring.datasource.url=jdbc:h2:mem:cliente
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=userdb
spring.datasource.password=passworddb
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
